name: publish-npm-package
on:
  release:
    types: [ published ]
jobs:
  npm-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kidneyweakx'

      - name: Install dependencies
        run: pnpm install
      - run: pnpm build

      - name: Publish Packages
        run: npm publish --access public
        working-directory: ./apps/odul
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
